#!/bin/bash
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export cwd_url=$(python -c "import pathlib; print(pathlib.Path.cwd().as_uri())")

# create pip source package:
# (sdist is a source distribution but
#  it can be changed to a binary wheel):
python setup.py sdist

# create conda source package:
# (it's 'noarch' at the moment but
#  it can be changed to a compiled binary):
conda build ./conda --output-folder ./dist
