#!/bin/bash
this_script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source="${this_script_dir}/setup/path-source"

# <custom vars>
source "${this_script_dir}/env/pre"
# </custom vars>


# <miniconda path confirmation>
_bin="bin"
_python="bin/python"
case "$(uname -s)" in
    MINGW*)
        _bin="Scripts"
        _python="python.exe" ;;
esac

miniconda_dir="~/miniconda3"
function yes_or_no {
    while true; do
        echo ""
        echo "Is Miniconda/Anaconda installed to \"${miniconda_dir}\"? (yes/no)"
        read -p "Type 'y' or 'n': " yn
        case $yn in
            [Yy]*) return 0 ;;  
            [Nn]*) return 1 ;;
            *) echo "Please type 'y' or 'n' only" ;;
        esac
    done
}

_conda="${miniconda_dir}/${_bin}/conda"
while true; do
    if [ -f "$_conda" ]; then
        yes_or_no && break
    else
        echo "\"${_conda}\" was not found!"
    fi
    echo ""
    echo "Please type the path to Miniconda/Anaconda folder."
    echo "(you can drag'n'drop or paste it right here)"
    read -p "Type the path (or 'x' to exit): " miniconda_dir
    _conda="${miniconda_dir}/${_bin}/conda"
    if [ "${miniconda_dir}" == "x" ]; then
        return 0
    fi
done
# </miniconda path confirmation>


# <main>
cd "${this_script_dir}"

export PYTHONNOUSERSITE=1
export PATH="${miniconda_dir}/${_bin}:$PATH"

"${miniconda_dir}/${_python}" "${this_script_dir}/setup/clear_global_channels.py" "${miniconda_dir}/${_bin}/conda"
conda env remove --name "$env"
conda env create --file "${this_script_dir}/env/$yaml"
# Do not specify custom -p/--prefix path as
# this might make shortcut creation fail.
# If you need so specify custom prefix
# first add ${miniconda_dir}/${_bin} to the PATH
. "$source" activate "$env"
# </main>


# <custom commands after activate>
source "${this_script_dir}/env/post"
# </custom commands after activate>


. "$source" deactivate
