#!/bin/bash
exi () { read -n 1 -s -r -p "Error occured. Press any key to exit" && exit 1; }
here="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


# <custom vars>
source "$here/env/pre" || exi
# </custom vars>


# <miniconda path confirmation>
_bin="bin"
_python="bin/python"
_conda="bin/conda"
if [[ "$OSTYPE" == "msys" ]]; then
    _bin="Scripts"
    _python="python.exe"
    _conda="Scripts/conda.exe"
fi

prefix="~/miniconda3"
function yes_or_no {
    while true; do
        echo ""
        echo "Is Miniconda/Anaconda installed to \"$prefix\"? (yes/no)"
        read -p "Type 'y' or 'n': " yn
        case $yn in
            [Yy]*) return 0 ;;  
            [Nn]*) return 1 ;;
            *) echo "Please type 'y' or 'n' only" ;;
        esac
    done
}

conda="$prefix/$_conda"
while true; do
    if [ -f "$conda" ]; then
        yes_or_no && break
    else
        echo "\"$conda\" was not found!"
    fi
    echo ""
    echo "Please type the path to Miniconda/Anaconda folder."
    echo "(you can drag'n'drop or paste it right here)"
    read -p "Type the path (or 'x' to exit): " prefix
    conda="$prefix/$_conda"
    if [ "$prefix" == "x" ]; then
        return 0
    fi
done
# </miniconda path confirmation>


cd "$here/env" || exi
export PYTHONNOUSERSITE=1
export PATH="$prefix/$_bin:$prefix/condabin:$PATH"

source "$(type -p activate)" base || exi

_cnd=conda
if [[ "$OSTYPE" == "msys" ]]; then
    _cnd="$(cygpath -w "$(type -p conda.exe)")"; fi
"$prefix/$_python" "$here/setup/clear_global_channels.py" "$_cnd" || exi

conda remove -n "$env" --all || exi
conda env remove -n "$env" || exi
conda update conda || exi
conda env create --file "$here/env/$yaml" || exi

conda deactivate || exi
source "$(type -p activate)" "$env" || exi


# <custom commands after activate>
cd "$here/env" || exi
source "$here/env/post" || exi
# </custom commands after activate>

conda deactivate
